version: '3.8'

networks:
  default:
    external: true
    name: mainNetwork


services:
    nginx:
        image: nginx:stable
        container_name: kmsPlant-App
        ports:
            - "8900:80"
        volumes:
            - .:/var/www/kmsPlant
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped


    php:
        build:
          context: ./docker
          dockerfile: Dockerfile
        container_name: kmsPlant-Php
        volumes:
          - .:/var/www/kmsPlant
          - ./docker/php/www.conf:/usr/local/etc/php/conf.d/www.conf
          - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        restart: unless-stopped

