FROM php:8.0-fpm

RUN sed -i 's/9000/9900/' /usr/local/etc/php-fpm.d/zz-docker.conf

WORKDIR /var/www/kmsPlant

ENV TZ=Asia/Manila


RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
    && apt-get install -y\
    curl \
    zip \
    unzip


RUN apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN docker-php-ext-install pdo pdo_mysql 


RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www


# Copy existing application directory permissions
COPY --chown=www:www . /var/www/kmsPlant

# Change current user to www
USER www

#EXPOSE 9000
CMD ["php-fpm"]
